package io;

import java.io.*;
import java.util.*;

/**
 * class to read a trace file, for example as generated by one of the models, or even real data (but make sure it is in the same format)
 * typical format is:
 * # header line
 * T S I R
 * 0 100 1 0 etc
 * (tab delimited)
 * 
 * @author Samantha Lycett
 * @created 9 Dec 2013
 * @version 9 Dec 2013
 */
public class TraceFileReader {

	String 			filename;
	String[] 		colnames;
	String			delim = "\t";
	
	List<String> 	header;
	String 			headerDelim = "#";
	
	public TraceFileReader() {
		
	}
	
	/////////////////////////////////////////////////////////
	
	public void setFilename(String filename) {
		this.filename = filename;
	}
	
	public void setDelim(String delim) {
		this.delim = delim;
	}
	
	public void setHeaderDelim(String hd) {
		this.headerDelim = hd;
	}
	
	/////////////////////////////////////////////////////////
	
	/**
	 * all in one method - opens the file from specified filename, reads & returns the data, closes the file
	 * @param filename
	 * @return
	 */
	public List<Double[]> readData(String filename) {
		this.filename = filename;
		return readData();
	}
	
	/**
	 * opens the file from already set filename, reads & returns the data, closes the file
	 * @return
	 */
	public List<Double[]> readData() {
		
		try {
			Scanner inFile 	= new Scanner(new File(filename));
		
			header			= new ArrayList<String>();
			String line 	= inFile.nextLine();
			while (inFile.hasNext() && line.startsWith(headerDelim)) {
				header.add(line);
				
				//System.out.println(line);
				
				line 		= inFile.nextLine();
			}
			
			// line does not start with the # symbol, so must be the column names
			colnames = line.split(delim);
			
			List<Double[]> data = new ArrayList<Double[]>();
			while (inFile.hasNext()) {
				line 			= inFile.nextLine();
				String[] els 	= line.split(delim);
				Double[] dd 	=  new Double[els.length];
				
				for (int i = 0; i < els.length; i++) {
					dd[i] = Double.parseDouble(els[i]);
				}
				data.add(dd);
				
			}
			
			inFile.close();
			
			return data;
			
		} catch (IOException e) {
			e.printStackTrace();
			
			return null;
		}
		
	}
	
	public String[] getColumnNames() {
		return colnames;
	}
	
	public List<String> getHeader() {
		return header;
	}
}
